apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: _JAVA_OPTIONS
            value: ""
          - name: MAVEN_OPTS
            value: ""
          image: uses:bachu-org/jx3-pipeline-catalog/tasks/maven/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          volumeMounts:
          - mountPath: /root/.m2/
            name: maven-settings
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
        - name: build-set-version
          resources: {}
        - name: build-mvn-install
          resources: {}
          volumeMounts:
          - name: license-file
            mountPath: /home/jenkins/.mvnrepository/net/sf/saxon/saxon-ee/9.4.0.6/saxon-license.lic
            subPath: "saxon-license.lic"
        volumes:
        - name: maven-settings
          secret:
            secretName: jenkins-maven-settings
        - name: license-file
          secret:
            secretName: saxon-lic-file
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
